# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  end
  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  end

  config.vm.box = 'archlinux/archlinux'

  config.vm.synced_folder '..', '/vagrant', type: 'rsync',
    rsync__exclude: '.git',
    rsync__args: ['--verbose', '--archive', '-z', '--copy-links']

  config.vm.provision :shell, path: 'provision/archlinux-freeze.sh'
  config.vm.provision :shell, path: 'provision/salt-filetree.sh'
  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.install_type = 'git'
    salt.install_args = 'v2017.7.2'

    salt.verbose = true
    salt.log_level = 'warning'
    salt.colorize = true
    salt.run_highstate = true
    salt.minion_id = 'master'

    salt.salt_call_args = [
        '--file-root',   '/salt/states', 
        '--pillar-root', '/salt/pillar'
    ]
  end
  config.vm.provision :shell, inline: 'pacman -Qq python-pip || pacman -S --noconfirm python-pip'
  config.vm.provision :shell, path: 'provision/testinfra.sh'
end
